### ISSUE TITLE
I have an unusual error on macOS - How do i fix SDL2

### ISSUE THREAD

**Issue by 404oops** [OpenXbox/xbox-smartglass-nano-python#23]
```
Traceback (most recent call last):
  File "/Users/<username>/Library/Python/3.8/lib/python/site-packages/sdl2/dll.py", line 223, in <module>
    dll = DLL("SDL2", ["SDL2", "SDL2-2.0"], os.getenv("PYSDL2_DLL_PATH"))
  File "/Users/<username>/Library/Python/3.8/lib/python/site-packages/sdl2/dll.py", line 104, in __init__
    raise RuntimeError("could not find any library for %s (%s)" %
RuntimeError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<username>/Library/Python/3.8/bin/xbox-nano-client", line 5, in <module>
    from xbox.nano.scripts.client import main
  File "/Users/<username>/Library/Python/3.8/lib/python/site-packages/xbox/nano/scripts/client.py", line 12, in <module>
    from xbox.nano.render.client import SDLClient
  File "/Users/<username>/Library/Python/3.8/lib/python/site-packages/xbox/nano/render/client/__init__.py", line 2, in <module>
    from xbox.nano.render.client.sdl import SDLClient
  File "/Users/<username>/Library/Python/3.8/lib/python/site-packages/xbox/nano/render/client/sdl.py", line 2, in <module>
    from xbox.nano.render.video.sdl import SDLVideoRenderer
  File "/Users/<username>/Library/Python/3.8/lib/python/site-packages/xbox/nano/render/video/sdl.py", line 5, in <module>
    import sdl2
  File "/Users/<username>/Library/Python/3.8/lib/python/site-packages/sdl2/__init__.py", line 2, in <module>
    from .dll import get_dll_file, _bind
  File "/Users/<username>/Library/Python/3.8/lib/python/site-packages/sdl2/dll.py", line 225, in <module>
    raise ImportError(exc)
ImportError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)
```

**Comment by tuxuser** [comment]
This should help: https://github.com/marcusva/py-sdl2#requirements

`pip install pysdl2-dll`
